hash_server/urls.py
from django.conf import settings
from django.conf.urls import url
from django.contrib import admin
from django.urls import path, include

import hashcat_server

urlpatterns = [
    url(r'admin/', admin.site.urls),
    url(r'^', include('hashcat_server.urls')),
    url(r'hashes/', include('hashcat_server.urls')),
]

if settings.DEBUG:
    import debug_toolbar
    urlpatterns = [
        path('__debug__/', include(debug_toolbar.urls)),

        # For django versions before 2.0:
        # url(r'^__debug__/', include(debug_toolbar.urls)),

    ] + urlpatterns

hashcat_server/urls.py
from django.conf.urls import url

from hashcat_server import views

app_name = "hashcat_sever"

urlpatterns = [
    url(r'^$', views.ShowTableOfHashes.as_view(), name='hashes'),
    url(r'^credentials$', views.RogueAPCredentials.as_view(), name='rogue_ap'),
    url(r'^new_hash$', views.save_new_value),
    url(r'^get_hashes_from_queue$', views.get_hashes_from_queue),
    url(r'^edit_hash_status$', views.edit_hash_status_using_json),
    url(r'^add_hash_value$', views.add_hash_value),
    url(r'^change_hashcat_status$', views.change_hashcat_status),
    url(r'^edit_status$', views.edit_hash_status, name="edit_hash"),
    url(r'^remove_hash$', views.remove_hash_from_list, name="remove_hash"),
    url(r'^hashcat_control$', views.check_hashcat_command, ),
    url(r'^hashcat_action$', views.hashcat_action, name="hashcat_action"),
    url(r'save_credentials', views.save_netcreds_output)
]

templates/bulma/base.html
{% load static bulma_tags %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>{% block title %}{% endblock title %}</title>
    {% block css %}
        <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.0.13/css/all.css" integrity="sha384-DNOHZ68U8hZfKXOrtjWvjxusGo9WQnrNx2sqG0tfsghAvtVlRW3tvkXWZh58N9jp" crossorigin="anonymous">
        <link rel="stylesheet" href="{% static 'bulma/css/style.css' %}">
        {% block extra_css %}{% endblock extra_css %}
    {% endblock css %}
</head>
<body>

{% block header %}
    <div class="container">
        <nav class="navbar">
            <div class="navbar-brand">
                <a class="navbar-item" href="/">
                    <img src="http://bulma.io/images/bulma-logo.png"
                         alt="Bulma: a modern CSS framework based on Flexbox"
                         width="112" height="28">
                </a>

                <a class="navbar-item is-hidden-desktop" href="https://github.com/jgthms/bulma" target="_blank">
        <span class="icon" style="color: #333;">
          <i class="fa fa-github"></i>
        </span>
                </a>

                <a class="navbar-item is-hidden-desktop" href="https://twitter.com/jgthms" target="_blank">
        <span class="icon" style="color: #55acee;">
          <i class="fa fa-twitter"></i>
        </span>
                </a>

                <div class="navbar-burger burger" data-target="navMenuExample">
                    <span></span>
                    <span></span>
                    <span></span>
                </div>
            </div>

            <div id="navMenuExample" class="navbar-menu">
                <div class="navbar-start">

                    <a class="navbar-item" href="{% url 'hashcat_sever:hashes' %}">Hashes</a>
                    <a class="navbar-item" href="{% url 'hashcat_sever:rogue_ap' %}">WiFi sniffer</a>
                </div>

                <div class="navbar-end">
                    {% url 'login' as login_url %}
                    {% if login_url %}
                        <a class="navbar-item is-hidden-desktop-only" href="{{ login_url }}">
                            Login
                        </a>
                    {% endif %}
                    {% url 'account_login' as login_url %}
                    {% if login_url %}
                        <a class="navbar-item is-hidden-desktop-only" href="{{ login_url }}">
                            Login (allauth)
                        </a>
                    {% endif %}
                    {% url 'account_signup' as signup_url %}
                    {% if signup_url %}
                        <a class="navbar-item is-hidden-desktop-only" href="{{ signup_url }}">
                            Signup (allauth)
                        </a>
                    {% endif %}
                </div>
            </div>
        </nav>
    </div>
{% endblock header %}

{% block hero %}{% endblock hero %}

<section class="section">
    <div class="container">
        {% block messages %}
            {% if messages %}
                {% for message in messages %}
                    <div class="notification is-success">
                        <button class="delete"></button>
                        {{ message }}
                    </div>
                {% endfor %}
            {% endif %}
        {% endblock messages %}

        {% block content_area %}
            {% block content_title %}{% endblock content_title %}
            {% block content %}{% endblock content %}
        {% endblock content_area %}
    </div>
</section>

{% block modal %}{% endblock modal %}

{% block footer %}
    <footer class="footer">
        <div class="container">
            <div class="content has-text-centered">
                <p>
                    <strong>FTLBerry</strong> by <a href="https://spodlesny.eu">Šimon Podlesný</a>
                </p>
                <p>
                <strong>Bulma</strong> by <a href="http://jgthms.com">Jeremy Thomas</a>.
                <strong>Django-Bulma</strong> by <a
                href="http://timonweb.com">Tim Kamanin</a>.
            </div>
        </div>
    </footer>
{% endblock footer %}

{% block javascript %}
    {% block extra_javascript %}{% endblock extra_javascript %}
{% endblock javascript %}
</body>
</html>