hash_server/urls.py
from django.conf import settings
from django.conf.urls import url
from django.contrib import admin
from django.urls import path, include

import hashcat_server

urlpatterns = [
    url(r'admin/', admin.site.urls),
    url(r'^', include('hashcat_server.urls')),
    url(r'hashes/', include('hashcat_server.urls')),
]

if settings.DEBUG:
    import debug_toolbar
    urlpatterns = [
        path('__debug__/', include(debug_toolbar.urls)),

        # For django versions before 2.0:
        # url(r'^__debug__/', include(debug_toolbar.urls)),

    ] + urlpatterns

hashcat_server/urls.py
from django.conf.urls import url

from hashcat_server import views

app_name = "hashcat_sever"

urlpatterns = [
    url(r'^$', views.ShowTableOfHashes.as_view(), name='hashes'),
    url(r'^credentials$', views.RogueAPCredentials.as_view(), name='rogue_ap'),
    url(r'^new_hash$', views.save_new_value),
    url(r'^get_hashes_from_queue$', views.get_hashes_from_queue),
    url(r'^edit_hash_status$', views.edit_hash_status_using_json),
    url(r'^add_hash_value$', views.add_hash_value),
    url(r'^change_hashcat_status$', views.change_hashcat_status),
    url(r'^edit_status$', views.edit_hash_status, name="edit_hash"),
    url(r'^remove_hash$', views.remove_hash_from_list, name="remove_hash"),
    url(r'^hashcat_control$', views.check_hashcat_command, ),
    url(r'^hashcat_action$', views.hashcat_action, name="hashcat_action"),
    url(r'save_credentials', views.save_netcreds_output)
]

hashcat_server/models.py
from django.db import models
from django.db.models.functions import datetime
from django.utils import timezone


# Create your models here.


class HashList(models.Model):
    hash = models.CharField(max_length=1024, primary_key=True)
    hash_type = models.IntegerField(default=5500)
    cracked_value = models.CharField(null=True, blank=True, max_length=1024)
    status = models.CharField(max_length=32, default="New")
    timestamp = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return "{} ({})".format(self.hash, self.cracked_value)


class HashcatControl(models.Model):
    statuses = (("DOWN", "Hashcat is not running."),
                ("TIMEOUT", "Hashcat is not responding."),
                ("UP", "Hashcat is running."),
                ("STOP", "Hashcat has been stopped."),
                ("RESTART", "Hashcat is being restarted."),
                ("NOT YET INITIALIZED", "Hashcat did not connect yet."))
    status = models.CharField(choices=statuses, default=statuses[-1][0], max_length=256)
    error = models.BooleanField(default=False)
    commands = (
        ("start", "start"),
        ("stop", "stop"),
        ("restart", "restart"),
    )
    command = models.CharField(choices=commands, default=commands[0][0], max_length=256)
    error_response = models.CharField(max_length=1024, blank=True, null=True)
    stdout = models.TextField(default="")
    stderr = models.TextField(default="")
    last_ping = models.DateTimeField(default=datetime.datetime.now)

class NetCredsOutput(models.Model):
    data = models.TextField(default="")

hashcat_server/views.py
import datetime
import json
import re

from django.core.serializers import serialize
from django.http import HttpResponse, HttpResponseRedirect
from django.utils import timezone

# Create your views here.
from django.urls import reverse
from django.views.decorators.csrf import csrf_exempt
from django.views.decorators.http import require_http_methods
from django.views.generic import TemplateView, ListView, DetailView

from hashcat_server.models import HashList, HashcatControl, NetCredsOutput


class ShowTableOfHashes(ListView):
    model = HashList
    template_name = 'table_of_hashes.html'
    ordering = ['-timestamp']

    def get_context_data(self, *, object_list=None, **kwargs):
        context = super(ShowTableOfHashes, self).get_context_data(**kwargs)
        try:
            context["hashcat_status"] = HashcatControl.objects.last().get_status_display()
            context["last_ping"] = HashcatControl.objects.last().last_ping
            context["ordered"]  = HashcatControl.objects.last().get_command_display()
        except AttributeError as err:
            context["hashcat_status"] = None
        try:
            # remove ANSI escaping (solution from: https://stackoverflow.com/a/14693789)
            ansi_escape = re.compile(r'\x1B\[[0-?]*[ -/]*[@-~]')
            stdout = HashcatControl.objects.last().stdout
            clean_stdout = ansi_escape.sub('', stdout)
            context["stdout"] = clean_stdout
        except AttributeError:
            context["stdout"] = None

        return context


class RogueAPCredentials(ListView):
    model = NetCredsOutput
    template_name = 'net-creds_output.html'


@csrf_exempt
def save_new_value(request):
    if request.method == "POST":
        request_data = json.loads(request.body)
        if request_data.get('hash') and request_data.get('hash_type'):
            row = HashList.objects.create(hash=request_data.get('hash'),
                                          hash_type=request_data.get('hash_type'))
            row.save()
            return HttpResponse(status=200)
        else:
            return HttpResponse(status=400)
    else:
        return HttpResponse(status=405)


@csrf_exempt
def edit_hash_status(request):
    if request.method == "POST":
        request_data = request.POST
        if request_data.get('hash') and request_data.get('status') and request_data.get('hash_type'):
            row, created = HashList.objects.get_or_create(hash=request_data.get('hash'),
                                                          hash_type=request_data.get('hash_type'))
            print(created)
            row.status = request_data.get('status')
            row.save()
            return HttpResponseRedirect(reverse('hashcat_sever:hashes'))
        else:
            return HttpResponse(status=400)
    else:
        return HttpResponse(status=405)


@csrf_exempt
def remove_hash_from_list(request):
    if request.method == "POST":
        request_data = request.POST
        if request_data.get('hash') and request_data.get('hash_type'):
            row = HashList.objects.get(hash=request_data.get('hash'), hash_type=request_data.get('hash_type'))
            row.delete()
            return HttpResponseRedirect(reverse('hashcat_sever:hashes'))
        else:
            return HttpResponse(status=400)
    else:
        return HttpResponse(status=405)

@csrf_exempt
def hashcat_action(request):
    if request.method == "POST":
        request_data = request.POST
        if request_data.get('action'):
            row = HashcatControl.objects.last()
            if row is None:
                row = HashcatControl.objects.create()
                print("First init for: HashcatControl")
            row.command = request_data.get('action')
            row.save()
            return HttpResponseRedirect(reverse('hashcat_sever:hashes'))
        else:
            return HttpResponse(status=400)
    else:
        return HttpResponse(status=405)


def check_hashcat_command(request):
    if request.method == "GET":
        data = HashcatControl.objects.last()
        if data is None:
            HashcatControl.objects.create()
            data = HashcatControl.objects.last()
            print("First init for: HashcatControl")

        json_data = serialize('json', [data, ])

        # Update time
        data.last_ping = timezone.now()
        data.save()
        return HttpResponse(json_data, content_type="application/json")
    else:
        return HttpResponse(status=405)


def get_hashes_from_queue(request):
    if request.method == "GET":
        data_set = HashList.objects.filter(status="In queue")
        json_data = serialize('json', data_set)
        return HttpResponse(json_data, content_type="application/json")
    else:
        return HttpResponse(status=405)

@csrf_exempt
@require_http_methods(["POST"])
def edit_hash_status_using_json(request):
    json_data = json.loads(request.body)
    hash_value = json_data.get("hash")
    new_status = json_data.get("status")
    hash_object = HashList.objects.get(hash=hash_value)
    hash_object.status = new_status
    hash_object.save()
    return HttpResponse(status=200)

@csrf_exempt
@require_http_methods(["POST"])
def add_hash_value(request):
    json_data = json.loads(request.body)
    hash_value = json_data.get("hash")
    cracked_value = json_data.get("value")
    hash_object = HashList.objects.get(hash=hash_value)
    hash_object.cracked_value = cracked_value
    hash_object.save()
    return HttpResponse(status=200)

@csrf_exempt
def change_hashcat_status(request):
    if request.method == "POST":
        data = json.loads(request.body)
        hashcat_control = HashcatControl.objects.last()
        if data.get("status"):
            hashcat_control.status = data.get('status')
            if data.get("status") == "RESTART":
                hashcat_control.command = "start"
            hashcat_control.save()

        hashcat_control.save()
        return HttpResponse(status=200)
    else:
        return HttpResponse(status=405)


@csrf_exempt
@require_http_methods(["POST"])
def save_netcreds_output(request):
    if b"Starting net-creds.py" in request.body:
        NetCredsOutput.objects.create(data=request.body.decode())
    else:
        row = NetCredsOutput.objects.last()

        # remove ANSI escaping (solution from: https://stackoverflow.com/a/14693789)
        ansi_escape = re.compile(r'\x1B\[[0-?]*[ -/]*[@-~]')
        new_data = request.body.decode()
        clean_new_data = ansi_escape.sub('', new_data)

        row.data = row.data+clean_new_data
        row.save()
    return HttpResponse(status=200)

hashcat_server/templates/net-creds_output.html
{% extends 'bulma/base.html' %}
{% block content %}
<p>{{ netcredsoutput_list.last.data|linebreaks }}</p>
{% endblock %}

hashcat_server/templates/table_of_hashes.html
{% extends 'bulma/base.html' %}
{% block content %}
    {% if hashlist_list %}
        <table class="table is-bordered is-striped is-narrow is-hoverable is-fullwidth">
            <thead>
            <tr>
                <th><abbr title="Hashcat mode">Hashcat mode</abbr></th>
                <th><abbr title="Timestamp">Timestamp</abbr></th>
                <th><abbr title="Hash">Hash</abbr></th>
                <th><abbr title="Status">Status</abbr></th>
                <th><abbr title="Password">Password</abbr></th>
                <th><abbr title="Action">Action</abbr></th>
            </tr>
            </thead>
            <tbody>
            <p>Hashcat control pannel:</p>
            <div class="field is-grouped has-addons">
                <form action="{% url 'hashcat_sever:hashcat_action' %}" method="post">
                    {% if ordered == "start" %}
                        <button type="submit" class="button is-text" disabled>Start</button>
                    {% else %}
                        <input type="hidden" name="action" value="start">
                        <button type="submit" class="button is-text">Start</button>
                    {% endif %}
                </form>
                <form action="{% url 'hashcat_sever:hashcat_action' %}" method="post">
                    {% if ordered == "stop" %}
                        <button type="submit" class="button is-text" disabled>Stop</button>
                    {% else %}
                        <input type="hidden" name="action" value="stop">
                        <button type="submit" class="button is-text">Stop</button>
                    {% endif %}
                </form>
                <form action="{% url 'hashcat_sever:hashcat_action' %}" method="post">
                    {% if ordered == "restart" %}
                        <button type="submit" class="button is-text" disabled>Restart</button>
                    {% else %}
                        <input type="hidden" name="action" value="restart">
                        <button type="submit" class="button is-text">Restart</button>
                    {% endif %}
                </form>
            </div>
            {% if hashcat_status %}
                <p>Status: <b>{{ hashcat_status }}</b></p>
                <p>Last ping from hashcat: <b>{{ last_ping }}</b></p>
            {% else %}
                <p>Status: <b>Hashcat status not provided</b></p>
            {% endif %}
            <br>
            {% for list in hashlist_list %}
                <tr>
                    <td>{{ list.hash_type }}</td>
                    <td>{{ list.timestamp }}</td>
                    <td>{{ list.hash }}</td>
                    {% if list.status == "cracked" %}
                        <td><b>{{ list.status }}</b></td>
                    {% else %}
                        <td>{{ list.status }}</td>
                    {% endif %}
                    <td>{{ list.cracked_value }}</td>
                    {% if list.status == "Cracked" or list.status == "In queue" or list.status == "Cracking..." %}
                        <td>
                            <form method="post" action="{% url "hashcat_sever:remove_hash" %}">
                                <input type="hidden" name="hash" value="{{ list.hash }}">
                                <input type="hidden" name="hash_type" value="{{ list.hash_type }}">
                                <button type="submit" class="button is-danger is-outlined">
                        <span class="icon">
                            <i class="fas fa-trash-alt"></i>
                        </span>
                                    <span>
                            Delete
                        </span>
                                </button>
                            </form>
                        </td>
                    {% else %}
                        <td>
                            <div class="field is-grouped has-addons">

                                <form method="post" action="{% url "hashcat_sever:edit_hash" %}">
                                    <input type="hidden" name="hash" value="{{ list.hash }}">
                                    <input type="hidden" name="status" value="In queue">
                                    <input type="hidden" name="hash_type" value="{{ list.hash_type }}">
                                    <button type="submit" class="button is-success">
                        <span class="icon">
                            <i class="fas fa-plus"></i>
                        </span>
                                        <span>
                            Add to queue
                        </span>
                                    </button>
                                </form>
                                &nbsp;&nbsp;
                                <form method="post" action="{% url "hashcat_sever:remove_hash" %}">
                                    <input type="hidden" name="hash" value="{{ list.hash }}">
                                    <input type="hidden" name="hash_type" value="{{ list.hash_type }}">
                                    <button type="submit" class="button is-danger is-outlined">
                        <span class="icon">
                            <i class="fas fa-trash-alt"></i>
                        </span>
                                        <span>
                            Delete
                        </span>
                                    </button>
                                </form>
                            </div>
                        </td>
                    {% endif %}
                </tr>
            {% endfor %}
            </tbody>
        </table>
    {% else %}
        <p>Error: Database is either empty or migration wasn't made</p>
    {% endif %}
{% endblock %}